# Chapter 23 — Personality Layer

## The Role of the Personality Layer

The personality layer is the final stage of the pipeline. It takes the raw execution results from the orchestrator — product arrays, cart confirmations, order data, error states — and converts them into a natural language response in the Be3 store's voice. It is not a simple template engine. It uses a large language model (Groq Llama 3.3 70B) to produce genuine, context-aware prose. But it does not hand the LLM raw data and hope for the best. Everything that goes into the prompt is deliberately scoped, trimmed, and guided by an intent-aware configuration system called the DCO.

The personality layer has two responsibilities: summarising the tool results into an LLM-safe format, and assembling the right system prompt for the specific intent that just ran. These two steps are kept separate because the summarisation is pure data transformation — no AI involved — while the prompt assembly is a configuration-driven decision about what instructions the AI needs.

---

## Step 1 — Tool Result Summarisation

Raw tool results can be enormous. A `product.search` might return 20 full product objects, each with long HTML descriptions, nested metadata, dozens of attribute fields, image arrays, and various API-specific fields the LLM has no use for. Sending all of this to the LLM wastes tokens, inflates cost, and risks pushing important instructions out of the context window.

`summarizeToolResultsForLLM()` strips each tool result down to only the fields the personality prompt actually needs. The transformation is tool-specific rather than generic — different tools get different treatments:

**For `product.search` and similar search tools**, products are trimmed to: `id`, `name`, `price`, `vendor`, `description` (capped at 160 chars), and `attributes` (first 12 keys only). The full list is capped at `MAX_PRODUCTS_FOR_LLM = 6`. This is the most important cap in the system — the LLM is not able to meaningfully reference more than 6 products in a conversational response, and giving it more just creates noise:

```js
base.products = productArray.slice(0, MAX_PRODUCTS_FOR_LLM).map(p => ({
    id:          p?.id || p?.handle || null,
    name:        p?.name || p?.title || null,
    price:       p?.price ?? null,
    vendor:      p?.vendor || p?.metadata?.vendor || null,
    description: p.description?.substring(0, 160) || null,
    attributes:  Object.keys(attrs).slice(0, 12).reduce(...)
}));
base.products_truncated = productArray.length > MAX_PRODUCTS_FOR_LLM;
base.total_products = productArray.length;
```

The `products_truncated` flag tells the LLM that more results exist, so it can say "and more" without hallucinating specific extra product names.

**For `cart.view`**, all line items are included (no truncation) because the cart response must be accurate — you cannot tell a user their cart has three items when it has five:

```js
base.cart_items = rr.items.map(i => ({
    id:       i?.id || null,
    name:     i?.product_name || i?.name || null,
    quantity: i?.quantity ?? null,
    price:    i?.price ?? null,
    subtotal: i?.subtotal ?? null
}));
base.total = rr.total ?? null;
```

**For `cart.add`**, the product name is extracted — prioritising the backend's authoritative name over the pipeline's param value:

```js
base.product_name = rr.product_name || tr.params?.product_name || null;
```

**For `vendor.list`**, vendors are capped at `MAX_VENDORS_FOR_LLM = 25` and trimmed to name, tag, product count, and delivery info. The `vendors_truncated` flag signals when the full list was cut.

**For `product.compare`**, the comparison array includes `expanded_attributes` with preference — these are human-readable attribute keys generated by the compare tool rather than raw backend codes:

```js
attributes: (() => {
    const attrs = p?.expanded_attributes || p?.attributes || p?.raw_attributes || null;
    // Prefer human-readable keys; cap at 24 attribute fields
    return attrs ? Object.keys(attrs).slice(0, 24).reduce(...) : null;
})()
```

**For `suggested_products`** (sentinel re-search results), product details are only included when `is_fallback` is false. If it's a fallback, the LLM doesn't receive the names — it's instructed to tell the user to "click the button to see suggestions" without naming specific products it cannot verify as relevant:

```js
if (!rr.is_fallback) {
    base.suggested_products = rr.suggested_products.slice(0, MAX_PRODUCTS_FOR_LLM).map(p => ({
        id: ..., name: ..., price: ..., whatsapp_link: ..., checkout_url: ...
    }));
}
```

The `search_mode` field is preserved when a search ran in `"similar"` mode. This prevents the LLM from saying "I found these products matching your query" when the correct framing is "here are products similar to the iPhone 16 you asked about."

---

## Step 2 — The Dynamic Context Orchestrator (DCO)

The DCO is the system that determines what system prompt gets built for each response. Before the DCO existed, the personality layer used a single monolithic prompt sent to every LLM call regardless of what the user asked. The problem: a prompt comprehensive enough to handle product comparisons, vendor contacts, checkout flows, and casual conversation was enormous — easily 800–1000 tokens of instructions — most of which was irrelevant to any single intent. An `add_to_cart` response does not need comparison formatting rules. A `vendor_contact` response does not need product grounding rules.

The DCO replaces this with a composable segment system. Each intent declares, in its config file, exactly which prompt segments it needs:

```js
// From add_to_cart.js intent config
dco: {
    segments:          ['core', 'formatting', 'grounding', 'gratitude'],
    storeContext:      'none',
    historyDepth:      2,
    includeSummary:    false,
    maxResponseTokens: 512
}

// From product_search.js intent config
dco: {
    segments:          ['core', 'formatting', 'grounding', 'suggestions', 'availability'],
    storeContext:      'lean',
    historyDepth:      4,
    includeSummary:    true,
    maxResponseTokens: 1024
}
```

The DCO loads these configs lazily from the intent config directory at first use and caches them for the lifetime of the process:

```js
function loadIntentDcoConfigs() {
    const files = fs.readdirSync(configDir).filter(f => f.endsWith('.js'));
    for (const file of files) {
        const config = require(path.join(configDir, file));
        if (config.name && config.dco) {
            intentDcoCache[config.name] = config.dco;
        }
    }
}
```

Intents that do not declare a `dco` key fall back to `DEFAULT_DCO`:

```js
const DEFAULT_DCO = {
    segments:          ['core', 'formatting', 'grounding', 'suggestions'],
    storeContext:      'none',
    historyDepth:      4,
    includeSummary:    true,
    maxResponseTokens: 1024
};
```

---

## The Prompt Segment Registry

Each segment is a small, focused function returning a string of approximately 30–150 tokens. They cover one specific concern each:

| Segment | Token cost | Purpose |
|---|---|---|
| `core` | ~150 | The Be3 personality: tone, emoji use, "never expose internals" rule |
| `formatting` | ~80 | WhatsApp formatting: no tables, bold for prices, lists for choices |
| `grounding` | ~120 | Truth rules: only mention products from results, never invent, price integrity |
| `suggestions` | ~100 | The `<suggestion>` XML block format for next-step proposals |
| `gratitude` | ~30 | Add warmth on cart/purchase actions |
| `comparison` | ~150 | Comparison structure: verdict first, best-for bullets, key differences |
| `similarity` | ~80 | Frames vector search results as "similar to X", not generic search |
| `capabilities` | ~100 | Answer "what can you do?" and handle impossible requests humorously |
| `availability` | ~80 | How to handle when a product is not in results (check store context) |
| `vendor_rules` | ~50 | Group products under vendor headings |
| `checkout_links` | ~80 | Never modify URLs, include all vendor breakdown fields |
| `visual_search` | ~80 | Trust visual match data; don't suggest keyword refinement |
| `suggested_products_grounding` | ~80 | Injected automatically when suggested_products exist |

The `comparison` segment, for example, is only in the DCO config for `product_compare` — a cart addition response never sees it and pays zero tokens for it. The `gratitude` segment is only active for `add_to_cart`, `checkout`, and similar purchase intents.

---

## Multi-Intent DCO Merging

When a message produces multiple intents (a stack run), the personality layer receives an array of intent names. The DCO merges their configs using four rules:

```js
// 1. Segments: UNION — all segments from all intents, de-duped, order preserved
const mergedSegments = [...new Set([...cfg1.segments, ...cfg2.segments])];

// 2. Store context: highest level wins (none < lean < full)
const highestContext = configs.reduce((best, cfg) =>
    CONTEXT_PRIORITY[cfg.storeContext] > CONTEXT_PRIORITY[best] ? cfg.storeContext : best
, 'none');

// 3. History depth: maximum across all intents
const historyDepth = Math.max(...configs.map(c => c.historyDepth));

// 4. Summary inclusion: true if ANY intent wants it
const includeSummary = configs.some(c => c.includeSummary);

// 5. Token budget: maximum across all intents
const maxResponseTokens = Math.max(...configs.map(c => c.maxResponseTokens));
```

This means a multi-intent response gets the union of all needed segments at the highest context level required by any constituent intent, with the most generous token budget. The response can be as rich as it needs to be without any intent's needs being silently dropped.

---

## Prompt Assembly: The Six-Step Build

`assemblePrompt()` builds the final system prompt in six steps:

**Step 1 — Segment injection**: Each segment in the merged DCO config is called and its output appended to `promptParts`. Segments that require dynamic arguments (like `similarity`, which needs the product name) receive them:

```js
for (const segmentKey of dco.segments) {
    const segmentFn = SEGMENTS[segmentKey];
    if (segmentKey === 'similarity' && options.similarityRef) {
        promptParts.push(segmentFn(options.similarityRef));
    } else if (typeof segmentFn === 'function') {
        promptParts.push(segmentFn());
    }
}
```

**Step 2 — Dynamic suggestion grounding**: If `toolResultsSummary` contains `"suggested_products"` and the `suggested_products_grounding` segment is not already in the config, it is automatically injected. This prevents a situation where suggestions exist but the LLM has no instructions on how to handle them.

**Step 3 — Store context injection**: If the DCO config requests store context (`lean` or `full`), the relevant store summary is embedded directly in the prompt:

```js
const ctx = dco.storeContext === 'full' ? getLeanContext() : getUltraLeanContext();
promptParts.push(`STORE CONTEXT:\n${JSON.stringify(ctx)}`);
```

`getUltraLeanContext()` returns just category names and product counts — minimal but enough for an availability check. `getLeanContext()` includes vendor names, category slugs, and basic attribute keys.

**Step 4 — Rescue context on failure**: When any tool fails and the intent would not normally get store context, an ultra-lean store summary is injected anyway under a `RESCUE CONTEXT` label. This gives the LLM something to work with when formulating a helpful recovery response — it can suggest alternative categories even when the search failed.

**Step 5 — Skipped/failed action instructions**: If actions were skipped (pronoun guard) or failed (circuit breaker), explicit instructions are injected:

```js
// Skipped:
promptParts.push(`SKIPPED ACTIONS: ... You MUST tell the user: "${skippedMessage}"`);

// Failed:
promptParts.push(`TOOL FAILURES: ... Do NOT pretend the failed action worked.\nFailed: ${JSON.stringify(failedToolsSummary)}`);
```

These injections override any LLM tendency to be vague about failures. The LLM is told explicitly what happened and told not to pretend otherwise.

**Step 6 — Tool results and verbosity hint**: The summarised tool results and an adaptive verbosity instruction are appended last:

```js
promptParts.push(`TOOL RESULTS DATA:\n${toolResultsSummary}`);
promptParts.push(`VERBOSITY: Be adaptive. Simple question → short and punchy. Details/comparison → be descriptive.`);
```

---

## Visual Search Prompt Pruning

A special rule applies when `options.visual_search` is true. The `visual_search` segment is force-added, and if the results contain products, the `grounding` and `availability` segments are removed:

```js
if (options.visual_search && hasProducts) {
    dco.segments = dco.segments.filter(s => s !== 'grounding' && s !== 'availability');
}
```

This is necessary because the grounding segment contains rules like "check store context before saying we don't have it" and "only mention products from results" — logic that makes sense for keyword searches but conflicts with visual search framing. A visual match should be presented with confidence, not hedged with availability checks.

---

## History Windowing

Instead of passing the full conversation history to every LLM call, the DCO's `getHistoryWindow()` takes only the last `historyDepth` messages from the raw history array. For intents like `add_to_cart` (depth 2), this means the LLM sees only the last exchange — there is no reason to give it five turns of context just to say "added to cart". For `conversation` or complex product discovery, depth 4 or 6 gives the LLM enough context to maintain coherent dialogue.

If a conversation summary is available (generated by a background summarisation process that compresses older history), it is injected as a system-level context message before the recent raw messages:

```js
messages.push({ role: 'system', content: `CONVERSATION CONTEXT: ${conversationSummary}` });
```

This gives the LLM context about what was discussed earlier without blowing out the context window with every raw turn.

---

## The LLM Call and Fail-Safe

The final call uses Groq's Llama 3.3 70B model at temperature 0.4 — warm enough to produce natural, varied prose, but not so high that it hallucinates or becomes inconsistent:

```js
const response = await queryGroqAI(messages, maxTokens, 0.4, 1, {}, GROQ_MODEL_ID);
```

The `maxTokens` comes from the DCO config — different intents get different budgets. A cart confirmation might cap at 512 tokens; a full product comparison might allow 1500.

If the LLM returns an empty response or throws an error, the fallback is a pre-existing message from the tool result itself — most tool handlers include a `message` field as a human-readable summary. If no tool message is available either, a safe generic fallback is returned:

```js
const primaryToolResult = toolResults.find(t => t.result && t.result.message);
return primaryToolResult
    ? primaryToolResult.result.message
    : "I've hit a small snag, but your request went through!";
```

---

*Next: Chapter 24 — The `<suggestion>` System*
