
/**
 * AUTO-GENERATED Semantic Clauses
 * Generated: 2026-04-09T04:17:41.295Z
 */
const CLAUSES = {
    "color_for_ladies": {
        "label": "color for ladies",
        "attribute": "color",
        "matches": [
            "red",
            "green",
            "blue",
            "yellow",
            "pink",
            "grey",
            "white"
        ],
        "display": {
            "prefix": "vibrant",
            "suffix": "for ladies"
        },
        "categories": [
            "ultrabooks",
            "kitchen_appliances",
            "sound_gadget",
            "iphones",
            "gadgets",
            "gaming",
            "sleepwear_&_loungewear",
            "kitchen",
            "appliances",
            "automobile",
            "food",
            "health_&_beauty",
            "supermarket_essentials",
            "sporting_goods",
            "toys,_kids_&_babies",
            "smartphones_&_tablets",
            "laptops_&_computers",
            "action_figures_&_collectibles",
            "air_conditioners",
            "all_in_one_pcs",
            "android_phones",
            "android_tablets",
            "baby_care",
            "beverages",
            "blenders",
            "business_laptops",
            "cctv",
            "cameras_&_photography",
            "canned_&_packaged_foods",
            "car_care",
            "car_electronics",
            "cases_&_covers",
            "chargers_&_cables",
            "cleaning_appliances",
            "components",
            "computing_accessories",
            "controller_&_game_pads",
            "cooking_appliances",
            "cookware_sets",
            "cooling",
            "cooling_system",
            "data_storage",
            "desktops",
            "dishwashing_supplies",
            "drones",
            "e-readers",
            "educational_toys",
            "electronics",
            "feature_phones",
            "fitness_&_exercise",
            "flight_stick",
            "food_preparation",
            "fragrances",
            "game_consoles",
            "gaming_accessories",
            "gaming_chairs_&_furnitures",
            "gaming_desktops",
            "gaming_laptops",
            "graphics_card",
            "hair_care",
            "home_audio",
            "household_cleaning",
            "interior_accessories",
            "ipad",
            "irons_&_steamers",
            "large_appliances",
            "laundry",
            "laundry_detergents",
            "makeup",
            "microwaves",
            "motherboards",
            "nintendo_switch",
            "outdoor_sports",
            "pc_cases_&_fans",
            "paper_&_plastic_products",
            "personal_care",
            "pet_supplies",
            "phone_accessories",
            "playstation",
            "power_banks",
            "power_solutions",
            "power_supplies_(psus)",
            "printers_&_scanners",
            "processors_(cpus)",
            "ram_&_storage",
            "racing_wheels",
            "refrigerators_&_freezers",
            "skin_care",
            "small_appliances",
            "smartphones",
            "snacks_&_confectionery",
            "surface_&_floor_cleaners",
            "tablets",
            "team_sports",
            "television_&_video",
            "vr_&_ar_headset",
            "vacuum_cleaners",
            "washing_machines_&_dryers",
            "wearable_tech",
            "windows_tablets",
            "workstations",
            "xbox",
            "laptops"
        ],
        "excluded_categories": [
            "fashion"
        ]
    },
    "color_for_men": {
        "label": "color for men",
        "attribute": "color",
        "matches": [
            "black",
            "brown"
        ],
        "display": {
            "prefix": "",
            "suffix": "for men"
        },
        "categories": [
            "ultrabooks",
            "kitchen_appliances",
            "sound_gadget",
            "iphones",
            "gadgets",
            "gaming",
            "appliances",
            "automobile",
            "food",
            "health_&_beauty",
            "supermarket_essentials",
            "sporting_goods",
            "toys,_kids_&_babies",
            "smartphones_&_tablets",
            "laptops_&_computers",
            "action_figures_&_collectibles",
            "air_conditioners",
            "all_in_one_pcs",
            "android_phones",
            "android_tablets",
            "baby_care",
            "beverages",
            "business_laptops",
            "cctv",
            "cameras_&_photography",
            "canned_&_packaged_foods",
            "car_care",
            "car_electronics",
            "cases_&_covers",
            "chargers_&_cables",
            "cleaning_appliances",
            "components",
            "computing_accessories",
            "controller_&_game_pads",
            "cooking_appliances",
            "cooling",
            "cooling_system",
            "data_storage",
            "desktops",
            "dishwashing_supplies",
            "drones",
            "e-readers",
            "educational_toys",
            "electronics",
            "feature_phones",
            "fitness_&_exercise",
            "flight_stick",
            "food_preparation",
            "fragrances",
            "game_consoles",
            "gaming_accessories",
            "gaming_chairs_&_furnitures",
            "gaming_desktops",
            "gaming_laptops",
            "graphics_card",
            "hair_care",
            "home_audio",
            "household_cleaning",
            "interior_accessories",
            "ipad",
            "irons_&_steamers",
            "large_appliances",
            "laundry",
            "laundry_detergents",
            "makeup",
            "microwaves",
            "motherboards",
            "nintendo_switch",
            "outdoor_sports",
            "pc_cases_&_fans",
            "paper_&_plastic_products",
            "personal_care",
            "pet_supplies",
            "phone_accessories",
            "playstation",
            "power_banks",
            "power_solutions",
            "power_supplies_(psus)",
            "printers_&_scanners",
            "processors_(cpus)",
            "ram_&_storage",
            "racing_wheels",
            "refrigerators_&_freezers",
            "skin_care",
            "small_appliances",
            "smartphones",
            "snacks_&_confectionery",
            "surface_&_floor_cleaners",
            "tablets",
            "team_sports",
            "television_&_video",
            "vr_&_ar_headset",
            "vacuum_cleaners",
            "washing_machines_&_dryers",
            "wearable_tech",
            "windows_tablets",
            "workstations",
            "xbox",
            "laptops"
        ],
        "excluded_categories": [
            "fashion",
            "sleepwear_&_loungewear",
            "kitchen"
        ]
    },
    "neutrals": {
        "label": "Neutrals",
        "attribute": "color",
        "matches": [
            "black",
            "grey",
            "white",
            "tan",
            "navy",
            "beige",
            "silver"
        ],
        "display": {
            "prefix": "Classic Neutral",
            "suffix": ""
        },
        "categories": [
            "ultrabooks",
            "kitchen_appliances",
            "sound_gadget",
            "iphones",
            "fashion",
            "sleepwear_&_loungewear",
            "accessories",
            "activewear",
            "boots",
            "bottoms_&_pants",
            "footwear",
            "formal_&_dress_shoes",
            "handbags",
            "handbags_&_bags",
            "jackets_&_outerwear",
            "jersey",
            "jewellery",
            "sandals_&_slippers",
            "shirts",
            "shoes",
            "sneakers_&_athletic",
            "tshirts",
            "tops_&_t-shirts",
            "watches_&_eyewear",
            "clothing"
        ],
        "excluded_categories": [
            "gadgets",
            "gaming",
            "kitchen",
            "appliances",
            "automobile",
            "food",
            "health_&_beauty",
            "supermarket_essentials",
            "sporting_goods",
            "toys,_kids_&_babies",
            "smartphones_&_tablets",
            "laptops_&_computers"
        ]
    },
    "apple_product": {
        "label": "apple product",
        "attribute": "brand",
        "matches": [
            "apple"
        ],
        "display": {
            "prefix": "",
            "suffix": "by apple"
        },
        "categories": [
            "business_laptops",
            "components",
            "cooling_system",
            "graphics_card",
            "ram_&_storage",
            "ultrabooks",
            "fashion",
            "gaming",
            "android_phones",
            "android_tablets",
            "windows_tablets",
            "smartphones_&_tablets",
            "laptops_&_computers",
            "accessories",
            "activewear",
            "all_in_one_pcs",
            "boots",
            "bottoms_&_pants",
            "cases_&_covers",
            "chargers_&_cables",
            "computing_accessories",
            "controller_&_game_pads",
            "data_storage",
            "desktops",
            "e-readers",
            "feature_phones",
            "flight_stick",
            "footwear",
            "formal_&_dress_shoes",
            "game_consoles",
            "gaming_accessories",
            "gaming_chairs_&_furnitures",
            "gaming_desktops",
            "gaming_laptops",
            "handbags",
            "handbags_&_bags",
            "ipad",
            "iphones",
            "jackets_&_outerwear",
            "jersey",
            "jewellery",
            "motherboards",
            "nintendo_switch",
            "pc_cases_&_fans",
            "phone_accessories",
            "playstation",
            "power_banks",
            "power_supplies_(psus)",
            "printers_&_scanners",
            "processors_(cpus)",
            "racing_wheels",
            "sandals_&_slippers",
            "shirts",
            "shoes",
            "sleepwear_&_loungewear",
            "smartphones",
            "sneakers_&_athletic",
            "tshirts",
            "tablets",
            "tops_&_t-shirts",
            "vr_&_ar_headset",
            "watches_&_eyewear",
            "wearable_tech",
            "workstations",
            "xbox",
            "clothing",
            "laptops"
        ],
        "excluded_categories": []
    },
    "infinix_product": {
        "label": "infinix product",
        "attribute": "brand",
        "matches": [
            "infinix"
        ],
        "display": {
            "prefix": "",
            "suffix": "by infinix"
        },
        "categories": [
            "business_laptops",
            "components",
            "cooling_system",
            "graphics_card",
            "ram_&_storage",
            "ultrabooks",
            "fashion",
            "gaming",
            "android_phones",
            "android_tablets",
            "windows_tablets",
            "smartphones_&_tablets",
            "laptops_&_computers",
            "accessories",
            "activewear",
            "all_in_one_pcs",
            "boots",
            "bottoms_&_pants",
            "cases_&_covers",
            "chargers_&_cables",
            "computing_accessories",
            "controller_&_game_pads",
            "data_storage",
            "desktops",
            "e-readers",
            "feature_phones",
            "flight_stick",
            "footwear",
            "formal_&_dress_shoes",
            "game_consoles",
            "gaming_accessories",
            "gaming_chairs_&_furnitures",
            "gaming_desktops",
            "gaming_laptops",
            "handbags",
            "handbags_&_bags",
            "ipad",
            "iphones",
            "jackets_&_outerwear",
            "jersey",
            "jewellery",
            "motherboards",
            "nintendo_switch",
            "pc_cases_&_fans",
            "phone_accessories",
            "playstation",
            "power_banks",
            "power_supplies_(psus)",
            "printers_&_scanners",
            "processors_(cpus)",
            "racing_wheels",
            "sandals_&_slippers",
            "shirts",
            "shoes",
            "sleepwear_&_loungewear",
            "smartphones",
            "sneakers_&_athletic",
            "tshirts",
            "tablets",
            "tops_&_t-shirts",
            "vr_&_ar_headset",
            "watches_&_eyewear",
            "wearable_tech",
            "workstations",
            "xbox",
            "clothing",
            "laptops"
        ],
        "excluded_categories": []
    },
    "microsoft_product": {
        "label": "Microsoft product",
        "attribute": "brand",
        "matches": [
            "microsoft"
        ],
        "display": {
            "prefix": "Microsoft",
            "suffix": ""
        },
        "categories": [
            "business_laptops",
            "components",
            "cooling_system",
            "graphics_card",
            "ram_&_storage",
            "ultrabooks",
            "fashion",
            "gaming",
            "android_phones",
            "android_tablets",
            "windows_tablets",
            "smartphones_&_tablets",
            "laptops_&_computers",
            "accessories",
            "activewear",
            "all_in_one_pcs",
            "boots",
            "bottoms_&_pants",
            "cases_&_covers",
            "chargers_&_cables",
            "computing_accessories",
            "controller_&_game_pads",
            "data_storage",
            "desktops",
            "e-readers",
            "feature_phones",
            "flight_stick",
            "footwear",
            "formal_&_dress_shoes",
            "game_consoles",
            "gaming_accessories",
            "gaming_chairs_&_furnitures",
            "gaming_desktops",
            "gaming_laptops",
            "handbags",
            "handbags_&_bags",
            "ipad",
            "iphones",
            "jackets_&_outerwear",
            "jersey",
            "jewellery",
            "motherboards",
            "nintendo_switch",
            "pc_cases_&_fans",
            "phone_accessories",
            "playstation",
            "power_banks",
            "power_supplies_(psus)",
            "printers_&_scanners",
            "processors_(cpus)",
            "racing_wheels",
            "sandals_&_slippers",
            "shirts",
            "shoes",
            "sleepwear_&_loungewear",
            "smartphones",
            "sneakers_&_athletic",
            "tshirts",
            "tablets",
            "tops_&_t-shirts",
            "vr_&_ar_headset",
            "watches_&_eyewear",
            "wearable_tech",
            "workstations",
            "xbox",
            "clothing",
            "laptops"
        ],
        "excluded_categories": []
    },
    "samsung_product": {
        "label": "samsung product",
        "attribute": "brand",
        "matches": [
            "samsung"
        ],
        "display": {
            "prefix": "samsung",
            "suffix": ""
        },
        "categories": [
            "business_laptops",
            "components",
            "cooling_system",
            "graphics_card",
            "ram_&_storage",
            "ultrabooks",
            "fashion",
            "gaming",
            "android_phones",
            "android_tablets",
            "windows_tablets",
            "smartphones_&_tablets",
            "laptops_&_computers",
            "accessories",
            "activewear",
            "all_in_one_pcs",
            "boots",
            "bottoms_&_pants",
            "cases_&_covers",
            "chargers_&_cables",
            "computing_accessories",
            "controller_&_game_pads",
            "data_storage",
            "desktops",
            "e-readers",
            "feature_phones",
            "flight_stick",
            "footwear",
            "formal_&_dress_shoes",
            "game_consoles",
            "gaming_accessories",
            "gaming_chairs_&_furnitures",
            "gaming_desktops",
            "gaming_laptops",
            "handbags",
            "handbags_&_bags",
            "ipad",
            "iphones",
            "jackets_&_outerwear",
            "jersey",
            "jewellery",
            "motherboards",
            "nintendo_switch",
            "pc_cases_&_fans",
            "phone_accessories",
            "playstation",
            "power_banks",
            "power_supplies_(psus)",
            "printers_&_scanners",
            "processors_(cpus)",
            "racing_wheels",
            "sandals_&_slippers",
            "shirts",
            "shoes",
            "sleepwear_&_loungewear",
            "smartphones",
            "sneakers_&_athletic",
            "tshirts",
            "tablets",
            "tops_&_t-shirts",
            "vr_&_ar_headset",
            "watches_&_eyewear",
            "wearable_tech",
            "workstations",
            "xbox",
            "clothing",
            "laptops"
        ],
        "excluded_categories": []
    },
    "hp_product": {
        "label": "HP product",
        "attribute": "brand",
        "matches": [
            "HP"
        ],
        "display": {
            "prefix": "HP",
            "suffix": ""
        },
        "categories": [
            "business_laptops",
            "components",
            "cooling_system",
            "graphics_card",
            "ram_&_storage",
            "ultrabooks",
            "fashion",
            "gaming",
            "android_phones",
            "android_tablets",
            "windows_tablets",
            "smartphones_&_tablets",
            "laptops_&_computers",
            "accessories",
            "activewear",
            "all_in_one_pcs",
            "boots",
            "bottoms_&_pants",
            "cases_&_covers",
            "chargers_&_cables",
            "computing_accessories",
            "controller_&_game_pads",
            "data_storage",
            "desktops",
            "e-readers",
            "feature_phones",
            "flight_stick",
            "footwear",
            "formal_&_dress_shoes",
            "game_consoles",
            "gaming_accessories",
            "gaming_chairs_&_furnitures",
            "gaming_desktops",
            "gaming_laptops",
            "handbags",
            "handbags_&_bags",
            "ipad",
            "iphones",
            "jackets_&_outerwear",
            "jersey",
            "jewellery",
            "motherboards",
            "nintendo_switch",
            "pc_cases_&_fans",
            "phone_accessories",
            "playstation",
            "power_banks",
            "power_supplies_(psus)",
            "printers_&_scanners",
            "processors_(cpus)",
            "racing_wheels",
            "sandals_&_slippers",
            "shirts",
            "shoes",
            "sleepwear_&_loungewear",
            "smartphones",
            "sneakers_&_athletic",
            "tshirts",
            "tablets",
            "tops_&_t-shirts",
            "vr_&_ar_headset",
            "watches_&_eyewear",
            "wearable_tech",
            "workstations",
            "xbox",
            "clothing",
            "laptops"
        ],
        "excluded_categories": []
    },
    "dell_product": {
        "label": "Dell product",
        "attribute": "brand",
        "matches": [
            "Dell"
        ],
        "display": {
            "prefix": "Dell",
            "suffix": ""
        },
        "categories": [
            "business_laptops",
            "components",
            "cooling_system",
            "graphics_card",
            "ram_&_storage",
            "ultrabooks",
            "fashion",
            "gaming",
            "android_phones",
            "android_tablets",
            "windows_tablets",
            "smartphones_&_tablets",
            "laptops_&_computers",
            "accessories",
            "activewear",
            "all_in_one_pcs",
            "boots",
            "bottoms_&_pants",
            "cases_&_covers",
            "chargers_&_cables",
            "computing_accessories",
            "controller_&_game_pads",
            "data_storage",
            "desktops",
            "e-readers",
            "feature_phones",
            "flight_stick",
            "footwear",
            "formal_&_dress_shoes",
            "game_consoles",
            "gaming_accessories",
            "gaming_chairs_&_furnitures",
            "gaming_desktops",
            "gaming_laptops",
            "handbags",
            "handbags_&_bags",
            "ipad",
            "iphones",
            "jackets_&_outerwear",
            "jersey",
            "jewellery",
            "motherboards",
            "nintendo_switch",
            "pc_cases_&_fans",
            "phone_accessories",
            "playstation",
            "power_banks",
            "power_supplies_(psus)",
            "printers_&_scanners",
            "processors_(cpus)",
            "racing_wheels",
            "sandals_&_slippers",
            "shirts",
            "shoes",
            "sleepwear_&_loungewear",
            "smartphones",
            "sneakers_&_athletic",
            "tshirts",
            "tablets",
            "tops_&_t-shirts",
            "vr_&_ar_headset",
            "watches_&_eyewear",
            "wearable_tech",
            "workstations",
            "xbox",
            "clothing",
            "laptops"
        ],
        "excluded_categories": []
    },
    "affordable": {
        "label": "affordable",
        "attribute": "price tier",
        "matches": [
            "budget",
            "midrange"
        ],
        "display": {
            "prefix": "cheap",
            "suffix": ""
        },
        "categories": [
            "tablets",
            "desktops",
            "smartphones",
            "gaming",
            "ultrabooks",
            "laptops_&_computers",
            "all_in_one_pcs",
            "android_phones",
            "android_tablets",
            "business_laptops",
            "computing_accessories",
            "controller_&_game_pads",
            "data_storage",
            "flight_stick",
            "game_consoles",
            "gaming_accessories",
            "gaming_chairs_&_furnitures",
            "gaming_desktops",
            "gaming_laptops",
            "ipad",
            "iphones",
            "motherboards",
            "nintendo_switch",
            "pc_cases_&_fans",
            "playstation",
            "power_supplies_(psus)",
            "printers_&_scanners",
            "processors_(cpus)",
            "racing_wheels",
            "vr_&_ar_headset",
            "windows_tablets",
            "workstations",
            "xbox",
            "laptops"
        ],
        "excluded_categories": [
            "components",
            "cooling_system",
            "graphics_card",
            "ram_&_storage"
        ]
    },
    "expensive": {
        "label": "expensive",
        "attribute": "price tier",
        "matches": [
            "premium",
            "flagship"
        ],
        "display": {
            "prefix": "High End",
            "suffix": ""
        },
        "categories": [
            "components",
            "cooling_system",
            "graphics_card",
            "ram_&_storage",
            "tablets",
            "desktops",
            "smartphones",
            "gaming",
            "ultrabooks",
            "laptops_&_computers",
            "all_in_one_pcs",
            "android_phones",
            "android_tablets",
            "business_laptops",
            "computing_accessories",
            "controller_&_game_pads",
            "data_storage",
            "flight_stick",
            "game_consoles",
            "gaming_accessories",
            "gaming_chairs_&_furnitures",
            "gaming_desktops",
            "gaming_laptops",
            "ipad",
            "iphones",
            "motherboards",
            "nintendo_switch",
            "pc_cases_&_fans",
            "playstation",
            "power_supplies_(psus)",
            "printers_&_scanners",
            "processors_(cpus)",
            "racing_wheels",
            "vr_&_ar_headset",
            "windows_tablets",
            "workstations",
            "xbox",
            "laptops"
        ],
        "excluded_categories": []
    },
    "male": {
        "label": "male",
        "attribute": "Gender",
        "matches": [
            "male"
        ],
        "display": {
            "prefix": "Men's",
            "suffix": ""
        },
        "categories": [
            "fashion",
            "handbags",
            "accessories",
            "activewear",
            "boots",
            "bottoms_&_pants",
            "footwear",
            "formal_&_dress_shoes",
            "handbags_&_bags",
            "jackets_&_outerwear",
            "jersey",
            "jewellery",
            "sandals_&_slippers",
            "shirts",
            "shoes",
            "sleepwear_&_loungewear",
            "sneakers_&_athletic",
            "tshirts",
            "tops_&_t-shirts",
            "watches_&_eyewear",
            "clothing"
        ],
        "excluded_categories": []
    },
    "female": {
        "label": "female",
        "attribute": "Gender",
        "matches": [
            "female"
        ],
        "display": {
            "prefix": "Women's",
            "suffix": ""
        },
        "categories": [
            "fashion",
            "accessories",
            "activewear",
            "boots",
            "bottoms_&_pants",
            "footwear",
            "formal_&_dress_shoes",
            "handbags_&_bags",
            "jackets_&_outerwear",
            "jersey",
            "jewellery",
            "sandals_&_slippers",
            "shirts",
            "shoes",
            "sleepwear_&_loungewear",
            "sneakers_&_athletic",
            "tshirts",
            "tops_&_t-shirts",
            "watches_&_eyewear",
            "clothing"
        ],
        "excluded_categories": [
            "handbags"
        ]
    },
    "leather": {
        "label": "leather",
        "attribute": "material",
        "matches": [
            "leather"
        ],
        "display": {
            "prefix": "leather",
            "suffix": ""
        },
        "categories": [
            "iphones",
            "sound_gadget",
            "gadgets",
            "smartphones",
            "fashion",
            "kitchen_appliances",
            "smartphones_&_tablets",
            "accessories",
            "activewear",
            "all_in_one_pcs",
            "android_phones",
            "android_tablets",
            "boots",
            "bottoms_&_pants",
            "business_laptops",
            "cctv",
            "cameras_&_photography",
            "cases_&_covers",
            "chargers_&_cables",
            "components",
            "computing_accessories",
            "cooling_system",
            "data_storage",
            "desktops",
            "drones",
            "e-readers",
            "electronics",
            "feature_phones",
            "footwear",
            "formal_&_dress_shoes",
            "gaming_desktops",
            "gaming_laptops",
            "graphics_card",
            "handbags",
            "handbags_&_bags",
            "home_audio",
            "ipad",
            "jackets_&_outerwear",
            "jersey",
            "jewellery",
            "laptops_&_computers",
            "motherboards",
            "pc_cases_&_fans",
            "phone_accessories",
            "power_banks",
            "power_supplies_(psus)",
            "printers_&_scanners",
            "processors_(cpus)",
            "ram_&_storage",
            "sandals_&_slippers",
            "shirts",
            "shoes",
            "sleepwear_&_loungewear",
            "sneakers_&_athletic",
            "tshirts",
            "tablets",
            "television_&_video",
            "tops_&_t-shirts",
            "watches_&_eyewear",
            "wearable_tech",
            "windows_tablets",
            "workstations",
            "clothing",
            "laptops",
            "ultrabooks"
        ],
        "excluded_categories": []
    },
    "high_quality": {
        "label": "High quality",
        "attribute": "quality",
        "matches": [
            "Grade A"
        ],
        "display": {
            "prefix": "High quality",
            "suffix": ""
        },
        "categories": [
            "fashion",
            "kitchen_appliances",
            "accessories",
            "activewear",
            "boots",
            "bottoms_&_pants",
            "footwear",
            "formal_&_dress_shoes",
            "handbags",
            "handbags_&_bags",
            "jackets_&_outerwear",
            "jersey",
            "jewellery",
            "sandals_&_slippers",
            "shirts",
            "shoes",
            "sleepwear_&_loungewear",
            "sneakers_&_athletic",
            "tshirts",
            "tops_&_t-shirts",
            "watches_&_eyewear",
            "clothing"
        ],
        "excluded_categories": []
    },
    "small_storage": {
        "label": "small storage",
        "attribute": "storage",
        "matches": [
            "200"
        ],
        "display": {
            "prefix": "small storage",
            "suffix": ""
        },
        "categories": [
            "android_phones",
            "iphones",
            "gadgets",
            "smartphones_&_tablets",
            "all_in_one_pcs",
            "android_tablets",
            "business_laptops",
            "cctv",
            "cameras_&_photography",
            "cases_&_covers",
            "chargers_&_cables",
            "components",
            "computing_accessories",
            "cooling_system",
            "data_storage",
            "desktops",
            "drones",
            "e-readers",
            "electronics",
            "feature_phones",
            "gaming_desktops",
            "gaming_laptops",
            "graphics_card",
            "home_audio",
            "ipad",
            "laptops_&_computers",
            "motherboards",
            "pc_cases_&_fans",
            "phone_accessories",
            "power_banks",
            "power_supplies_(psus)",
            "printers_&_scanners",
            "processors_(cpus)",
            "ram_&_storage",
            "smartphones",
            "tablets",
            "television_&_video",
            "wearable_tech",
            "windows_tablets",
            "workstations",
            "laptops",
            "ultrabooks"
        ],
        "excluded_categories": [
            "sound_gadget"
        ]
    },
    "xl": {
        "label": "xl",
        "attribute": "size",
        "matches": [
            "xl"
        ],
        "display": {
            "prefix": "xl size",
            "suffix": ""
        },
        "categories": [
            "fashion",
            "electronics",
            "iphones",
            "sound_gadget",
            "food",
            "kitchen_appliances",
            "accessories",
            "activewear",
            "beverages",
            "boots",
            "bottoms_&_pants",
            "cctv",
            "cameras_&_photography",
            "canned_&_packaged_foods",
            "drones",
            "footwear",
            "formal_&_dress_shoes",
            "handbags",
            "handbags_&_bags",
            "home_audio",
            "jackets_&_outerwear",
            "jersey",
            "jewellery",
            "sandals_&_slippers",
            "shirts",
            "shoes",
            "sleepwear_&_loungewear",
            "snacks_&_confectionery",
            "sneakers_&_athletic",
            "tshirts",
            "television_&_video",
            "tops_&_t-shirts",
            "watches_&_eyewear",
            "clothing"
        ],
        "excluded_categories": []
    }
};

function getClausesForCategory(categoryName) {
    const applicable = {};
    for (const [id, clause] of Object.entries(CLAUSES)) {
        if (clause.categories.includes(categoryName) && !clause.excluded_categories.includes(categoryName)) {
            applicable[id] = clause;
        }
    }
    return applicable;
}

module.exports = { CLAUSES, getClausesForCategory };
